########################## Config #############################

substitutions:
# Entities names
  room_name: "kitchen"
  device_name: ${room_name}thermostat
  thermostat_name: "${room_name} thermostat controller"
  relay_1_name: "${room_name} heater"
  relay_2_name: "${room_name} cooler"
  relay_3_name: "${room_name} radiator valve"
  relay_4_name: "${room_name} circulating pump"
  relay_5_name: "${room_name} fan"
  relay_6_name: "${room_name} dryer"
  relay_7_name: "${room_name} dryer valve"
  relay_8_name: "${room_name} dryer pump"
  temperature_sensor_name: "${room_name} temperature"
  humidity_sensor_name: "${room_name} humidity"
  light_sensor_name: "${room_name} light level"
  
# Temperature and humidity sensor parameters
  si7021_update_interval: "300s"
  temp_decimals: "1"
  hum_decimals: "0"
  
# Light sensor parameters
  light_update_interval: "300s"
  light_decimals: "0"

# Wifi signal sensor
  wifi_update_interval: "300s"
  
# Rotary encoder with push button parameters
  button_debounce_time: "10ms"
  click_min_length: "50ms"
  click_max_length: "350ms"
  long_press_min_length: "500ms"
  long_press_max_length: "1000ms"
  encoder_resolution: "1" # Possible values: 1,2,4

# Buzzer parameters
  click_sound: "cick:d=1,o=5,b=100:e6"
  long_press_sound: "long:d=1,o=5,b=100:e6"
  
# Thermostat parameters
  default_low_t: "20 °C"
  default_high_t: "25 °C"
  visual_min_t: "15 °C"
  visual_max_t: "30 °C"
  cooling_off_time: "0s"
  cooling_run_time: "0s"
  heating_off_time: "0s"
  heating_run_time: "0s"
  idle_time: "0s"
  cooling_start_offset: "0.5 °C"
  cooling_stop_offset: "0.5 °C"
  heating_start_offset: "0.5 °C"
  heating_stop_offset: "0.5 °C"

# Display parameters
  display_model: "SSD1306 128x64"
  display_i2c_address: "0x3C"
  
# ESP8266 PIN configuration
  light_sensor_pin: "A0"
  button_pin: "D1"
  buzzer_pin: "D2"
  i2c_sda_pin: "D4"
  i2c_scl_pin: "D5"
  rotary_encoder_pin_a: "D6"
  rotary_encoder_pin_b: "D7"

# PCF8574 I/O Expander parameters
  exp_i2c_address: "0x20"
  
# PCF8574 I/O Expander PIN configuration  
  relay_1_pin: "0"
  relay_2_pin: "1"
  relay_3_pin: "2"
  relay_4_pin: "3"
  relay_5_pin: "4"
  relay_6_pin: "5"
  relay_7_pin: "6"
  relay_8_pin: "7"
  
  
##################### End of Config #####################################

esphome:
  name: ${device_name}

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "ac8294f43c830be40bf384280b0f5c04"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Thermostat Fallback Hotspot"
    password: "NEMwWiz0ek2c"

captive_portal:

# Enable I2C bus (GPIO4 for SDA and GPIO5 for SCL)
i2c:
  sda: ${i2c_sda_pin}
  scl: ${i2c_scl_pin}
  scan: true

# Buzzer configuration
output:
  - platform: esp8266_pwm
    pin: ${buzzer_pin}
    id: rtttl_out
rtttl:
  output: rtttl_out    

# Thermostat configuration
climate:
  - platform: thermostat
    id: this_thermostat
    name: ${thermostat_name}
    sensor: si7021_temperature_sensor
    default_target_temperature_low: ${default_low_t}
    default_target_temperature_high: ${default_high_t}
    visual:
      min_temperature: ${visual_min_t}
      max_temperature: ${visual_max_t}
    cool_deadband: ${cooling_start_offset}
    cool_overrun: ${cooling_stop_offset}
    heat_deadband: ${heating_start_offset}
    heat_overrun: ${heating_stop_offset}
    min_cooling_off_time: ${cooling_off_time}
    min_cooling_run_time: ${cooling_run_time}
    min_heating_off_time: ${heating_off_time}
    min_heating_run_time: ${heating_run_time}
    min_idle_time: ${idle_time}
    cool_action:
      - switch.turn_on: relay_2
      - switch.turn_on: relay_3
      - switch.turn_on: relay_4
    heat_action:
      - switch.turn_on: relay_1
      - switch.turn_on: relay_3
      - switch.turn_on: relay_4
    idle_action:
      - switch.turn_off: relay_1
      - switch.turn_off: relay_2
      - switch.turn_off: relay_3
      - switch.turn_off: relay_3

# PCF8574 I/O Expander configuration
pcf8574:
  - id: pcf8574_hub_1
    address: ${exp_i2c_address}
    pcf8575: false

# Switch configuration
switch:
# Relay 1
  - platform: gpio
    pin:
      pcf8574: pcf8574_hub_1
      number: ${relay_1_pin}
      mode:
        output: true
      inverted: false
    id: relay_1
    name: ${relay_1_name}
# Relay 2
  - platform: gpio
    pin:
      pcf8574: pcf8574_hub_1
      number: ${relay_2_pin}
      mode:
        output: true
      inverted: false
    id: relay_2
    name: ${relay_2_name}
# Relay 3
  - platform: gpio
    pin:
      pcf8574: pcf8574_hub_1
      number: ${relay_3_pin}
      mode:
        output: true
      inverted: false
    id: relay_3
    name: ${relay_3_name}
# Relay 4
  - platform: gpio
    pin:
      pcf8574: pcf8574_hub_1
      number: ${relay_4_pin}
      mode:
        output: true
      inverted: false
    id: relay_4
    name: ${relay_4_name}
# Relay 5
  - platform: gpio
    pin:
      pcf8574: pcf8574_hub_1
      number: ${relay_5_pin}
      mode:
        output: true
      inverted: false
    id: relay_5
    name: ${relay_5_name}
# Relay 6
  - platform: gpio
    pin:
      pcf8574: pcf8574_hub_1
      number: ${relay_6_pin}
      mode:
        output: true
      inverted: false
    id: relay_6
    name: ${relay_6_name}
# Relay 7
  - platform: gpio
    pin:
      pcf8574: pcf8574_hub_1
      number: ${relay_7_pin}
      mode:
        output: true
      inverted: false
    id: relay_7
    name: ${relay_7_name}
# Relay 8
  - platform: gpio
    pin:
      pcf8574: pcf8574_hub_1
      number: ${relay_8_pin}
      mode:
        output: true
      inverted: false
    id: relay_8
    name: ${relay_8_name}
   
#Sensors configuration
sensor:
# Wifi signal
  - platform: wifi_signal
    name: "WiFi signal"
    update_interval: ${wifi_update_interval}
# Temperature and humidity sensor configuration (Si7021 or HTU21D)
  - platform: htu21d
    temperature:
      id: si7021_temperature_sensor
      name: ${temperature_sensor_name}
      accuracy_decimals: ${temp_decimals}
    humidity:
      id: si7021_humidity_sensor
      name: ${humidity_sensor_name}
      accuracy_decimals: ${hum_decimals}
    update_interval: ${si7021_update_interval}
# Rotary Encoder 
  - platform: rotary_encoder
    name: "encoder"
    id: encoder
    internal: true
    resolution: ${encoder_resolution} 
    pin_a:
      number: ${rotary_encoder_pin_a}
      mode: INPUT_PULLUP
    pin_b:
      number: ${rotary_encoder_pin_b}
      mode: INPUT_PULLUP
# Photoresitor (Analog output)
  - platform: adc
    pin: ${light_sensor_pin}
    name: ${light_sensor_name}
    unit_of_measurement: "%"
    accuracy_decimals: ${light_decimals}
    update_interval: ${light_update_interval}
    filters:
      - multiply: 100   

# Binary sensors configuration
binary_sensor:
# Button (internal)
  - platform: gpio
    pin:
      number: ${button_pin}
      mode: INPUT_PULLUP
      inverted: true
    name: "Button"
    id: "button"
    internal: true
    filters:
      - delayed_on_off: ${button_debounce_time}
    on_click:
    - min_length: ${click_min_length}
      max_length: ${click_max_length}
      then:
        - rtttl.play: ${click_sound}
        - display.page.show_next: this_display
    - min_length: ${long_press_min_length}
      max_length: ${long_press_max_length}
      then:
        - rtttl.play: ${long_press_sound}

  
# Display configuration
display:
  - platform: ssd1306_i2c
    model: ${display_model}
    address: ${display_i2c_address}
    id: this_display
    pages:
      - id: page1
        lambda: |-
          it.circle(25, 25, 10);
      - id: page2
        lambda: |-
          it.filled_circle(50, 50, 10);

interval:
  - interval: 5s
    then:
      - display.page.show_next: this_display
      - component.update: this_display