########################## Config #############################

substitutions:
# Entities names
  room_name: "kitchen"
  device_name: ${room_name}thermostat
  thermostat_name: "${room_name} thermostat controller"
  relay_1_name: "${room_name} heater"
  relay_2_name: "${room_name} cooler"
  relay_3_name: "${room_name} radiator valve"
  relay_4_name: "${room_name} circulating pump"
  relay_5_name: "${room_name} fan"
  relay_6_name: "${room_name} dryer"
  relay_7_name: "${room_name} dryer valve"
  relay_8_name: "${room_name} dryer pump"
  temperature_sensor_name: "${room_name} temperature"
  humidity_sensor_name: "${room_name} humidity"
  v_sensor_name: "${room_name} thermostat output voltage"
  
# Temperature and humidity sensor parameters
  si7021_update_interval: "300s"
  temp_decimals: "1"
  hum_decimals: "1"
  
# Voltage sensor parameters
  v_update_interval: "600s"
  v_decimals: "1"
  v_esp8266_multiplier: "3.3" # ESP8266 internal voltage divider (3.3V->1V)
  v_correction_factor: "8.5" # The correct correction factor can be calculated dividing the real voltage value measured with a multimeter by the voltage value determined by the ESP8266 setting the correction factor to 8.5 [R1=7.5, R2=1K -> (R1+R2)/R2=8.5]  

# Wifi signal sensor
  wifi_update_interval: "10s"
  
# Rotary encoder with push button parameters
  button_debounce_time: "3ms"
  click_min_length: "50ms"
  click_max_length: "600ms"
  long_press_min_length: "601ms"
  long_press_max_length: "10000ms"
  encoder_resolution: "1" # Possible values: 1,2,4

# Buzzer parameters
  click_sound: "click:d=32,o=5,b=200:32g"
  long_press_sound: "long:d=8,o=5,b=200:8c"
  intro_sound: "A-Team:d=8,o=5,b=125:4d#6,a#,2d#6,16p,g#,4a#,4d#.,p,16g,16a#,d#6,a#,f6,2d#6,16p,c#.6,16c6,16a#,g#.,2a#"
  
# Thermostat parameters
  default_low_t: "20 °C"
  default_high_t: "25 °C"
  visual_min_t: "15 °C"
  visual_max_t: "30 °C"
  visual_temperature_step: "0.1 °C"
  cooling_off_time: "0s"
  cooling_run_time: "0s"
  heating_off_time: "0s"
  heating_run_time: "0s"
  idle_time: "0s"
  cooling_start_offset: "0.5 °C"
  cooling_stop_offset: "0.5 °C"
  heating_start_offset: "0.5 °C"
  heating_stop_offset: "0.5 °C"

# Display parameters
  display_model: "SSD1306 128x64"
  display_i2c_address: "0x3C"
  display_auto_off_time: "1 min"
  display_boot_page_time: "3s"
  
# ESP8266 PIN configuration
  v_sensor_pin: "A0"
  button_pin: "D1"
  buzzer_pin: "D2"
  i2c_sda_pin: "D4"
  i2c_scl_pin: "D5"
  rotary_encoder_pin_a: "D6"
  rotary_encoder_pin_b: "D7"

# PCF8574 I/O Expander parameters
  exp_i2c_address: "0x20"
  
# PCF8574 I/O Expander PIN configuration  
  relay_1_pin: "0"
  relay_2_pin: "1"
  relay_3_pin: "2"
  relay_4_pin: "3"
  relay_5_pin: "4"
  relay_6_pin: "5"
  relay_7_pin: "6"
  relay_8_pin: "7"
  
  
##################### End of Config #####################################

globals:
   - id: my_wifi_status
     type: bool
     restore_value: no

esphome:
  name: ${device_name}
  on_boot:
    priority: -100
    then:
      - display.page.show: page0
      - rtttl.play: ${intro_sound}
#      - delay: ${display_boot_page_time}
      - display.page.show: page1
      - script.execute: display_on_off
  

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "ac8294f43c830be40bf384280b0f5c04"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Thermostat Fallback Hotspot"
    password: "NEMwWiz0ek2c"

captive_portal:

# Enable I2C bus (GPIO4 for SDA and GPIO5 for SCL)
i2c:
  sda: ${i2c_sda_pin}
  scl: ${i2c_scl_pin}
  scan: true

# Buzzer configuration
output:
  - platform: esp8266_pwm
    pin: ${buzzer_pin}
    id: rtttl_out
rtttl:
  output: rtttl_out    

# Thermostat configuration
climate:
  - platform: thermostat
    id: this_thermostat
    name: ${thermostat_name}
    sensor: si7021_temperature_sensor
    default_target_temperature_low: ${default_low_t}
    default_target_temperature_high: ${default_high_t}
    visual:
      min_temperature: ${visual_min_t}
      max_temperature: ${visual_max_t}
      temperature_step: ${visual_temperature_step}
    cool_deadband: ${cooling_start_offset}
    cool_overrun: ${cooling_stop_offset}
    heat_deadband: ${heating_start_offset}
    heat_overrun: ${heating_stop_offset}
    min_cooling_off_time: ${cooling_off_time}
    min_cooling_run_time: ${cooling_run_time}
    min_heating_off_time: ${heating_off_time}
    min_heating_run_time: ${heating_run_time}
    min_idle_time: ${idle_time}
    cool_action:
      - switch.turn_on: relay_2
      - switch.turn_on: relay_3
      - switch.turn_on: relay_4
    heat_action:
      - switch.turn_on: relay_1
      - switch.turn_on: relay_3
      - switch.turn_on: relay_4
    dry_action:
      - switch.turn_on: relay_6
      - switch.turn_on: relay_7
      - switch.turn_on: relay_8
    idle_action:
      - switch.turn_off: relay_1
      - switch.turn_off: relay_2
      - switch.turn_off: relay_3
      - switch.turn_off: relay_4
      - switch.turn_off: relay_6
      - switch.turn_off: relay_7
      - switch.turn_off: relay_8
      

# PCF8574 I/O Expander configuration
pcf8574:
  - id: pcf8574_hub_1
    address: ${exp_i2c_address}
    pcf8575: false

# Switch configuration
switch:
# Relay 1
  - platform: gpio
    pin:
      pcf8574: pcf8574_hub_1
      number: ${relay_1_pin}
      mode:
        output: true
      inverted: false
    id: relay_1
    name: ${relay_1_name}
# Relay 2
  - platform: gpio
    pin:
      pcf8574: pcf8574_hub_1
      number: ${relay_2_pin}
      mode:
        output: true
      inverted: false
    id: relay_2
    name: ${relay_2_name}
# Relay 3
  - platform: gpio
    pin:
      pcf8574: pcf8574_hub_1
      number: ${relay_3_pin}
      mode:
        output: true
      inverted: false
    id: relay_3
    name: ${relay_3_name}
# Relay 4
  - platform: gpio
    pin:
      pcf8574: pcf8574_hub_1
      number: ${relay_4_pin}
      mode:
        output: true
      inverted: false
    id: relay_4
    name: ${relay_4_name}
# Relay 5
  - platform: gpio
    pin:
      pcf8574: pcf8574_hub_1
      number: ${relay_5_pin}
      mode:
        output: true
      inverted: false
    id: relay_5
    name: ${relay_5_name}
# Relay 6
  - platform: gpio
    pin:
      pcf8574: pcf8574_hub_1
      number: ${relay_6_pin}
      mode:
        output: true
      inverted: false
    id: relay_6
    name: ${relay_6_name}
# Relay 7
  - platform: gpio
    pin:
      pcf8574: pcf8574_hub_1
      number: ${relay_7_pin}
      mode:
        output: true
      inverted: false
    id: relay_7
    name: ${relay_7_name}
# Relay 8
  - platform: gpio
    pin:
      pcf8574: pcf8574_hub_1
      number: ${relay_8_pin}
      mode:
        output: true
      inverted: false
    id: relay_8
    name: ${relay_8_name}
   
#Sensors configuration
sensor:
# Wifi signal
  - platform: wifi_signal
    name: "WiFi signal"
    update_interval: ${wifi_update_interval}
    id: wifi_strength
# Temperature and humidity sensor configuration (Si7021 or HTU21D)
  - platform: htu21d
    temperature:
      id: si7021_temperature_sensor
      name: ${temperature_sensor_name}
      accuracy_decimals: ${temp_decimals}
    humidity:
      id: si7021_humidity_sensor
      name: ${humidity_sensor_name}
      accuracy_decimals: ${hum_decimals}
    update_interval: ${si7021_update_interval}
# Rotary Encoder 
  - platform: rotary_encoder
    name: "encoder"
    id: encoder
    internal: true
    resolution: ${encoder_resolution} 
    pin_a:
      number: ${rotary_encoder_pin_a}
      mode: INPUT_PULLUP
    pin_b:
      number: ${rotary_encoder_pin_b}
      mode: INPUT_PULLUP
# Voltage sensor (Analog output)
  - platform: adc
    pin: ${v_sensor_pin}
    name: ${v_sensor_name}
    id: v_sensor
    internal: true
    unit_of_measurement: "V"
    accuracy_decimals: ${v_decimals}
    update_interval: ${v_update_interval}
    filters:
      - multiply: ${v_esp8266_multiplier}
      - multiply: ${v_correction_factor}

# Binary sensors configuration
binary_sensor:
# Button 
  - platform: gpio
    pin:
      number: ${button_pin}
      mode: INPUT
      inverted: false
    name: "Button"
    id: "button"
    internal: true
    filters:
      - delayed_on_off: ${button_debounce_time}
    on_click:
    - min_length: ${click_min_length}
      max_length: ${click_max_length}
      then:
        - rtttl.play: ${click_sound}
        - if:
            condition:
              - script.is_running: display_on_off
            then:
              - script.execute: display_on_off
              - display.page.show_next: this_display
              - component.update: this_display
            else:
              - script.execute: display_on_off
              - display.page.show: page1
              - component.update: this_display
    - min_length: ${long_press_min_length}
      max_length: ${long_press_max_length}
      then:
        - rtttl.play: ${long_press_sound}
        - script.execute: display_on_off
        - display.page.show: page1
        - component.update: this_display
  
# Display configuration
display:
  - platform: ssd1306_i2c
    model: ${display_model}
    address: ${display_i2c_address}
    id: this_display
    pages:
      - id: page0
        lambda: |-
          it.printf(0, 10, id(font2), "d-diot");
      - id: page1
        lambda: |-
          if (id(this_thermostat).action == 0) {
            it.printf(it.get_width(), 49, id(font3), TextAlign::RIGHT, "Off");
          }
          if (id(this_thermostat).action == 2) {
            it.printf(it.get_width(), 49, id(font3), TextAlign::RIGHT, "Cooling");
          }
          if (id(this_thermostat).action == 3) {
            it.printf(it.get_width(), 49, id(font3), TextAlign::RIGHT, "Heating");
          }
          if (id(this_thermostat).action == 4) {
            it.printf(it.get_width(), 49, id(font3), TextAlign::RIGHT, "Idle");
          }
          if (id(this_thermostat).action == 5) {
            it.printf(it.get_width(), 49, id(font3), TextAlign::RIGHT, "Drying");
          }
          if (id(this_thermostat).action == 6) {
            it.printf(it.get_width(), 49, id(font3), TextAlign::RIGHT, "Fan");
          }
          if (id(my_wifi_status) == false) {
            it.image(0, 0, id(wifi_no_signal));
          } else {
            if (id(wifi_strength).state > -80) {
              it.image(0, 0, id(wifi_4));
            }
          }
          it.line(0, 19, 128, 19);
          it.printf(0, 22, id(font1), "%.1f°C", id(si7021_temperature_sensor).state);
          it.printf(it.get_width(), 22, id(font1), TextAlign::RIGHT, "%.1f%%", id(si7021_humidity_sensor).state);
          it.line(0, 45, 128, 45);
          if (id(this_thermostat).mode == 0) {
            it.image(55, 48, id(power_standby_icon));
            it.printf(0, 49, id(font3), "OFF");
          }
          if (id(this_thermostat).mode == 1) {
            it.image(55, 48, id(sync_icon));
            it.printf(0, 49, id(font3), "H-C");
          }
          if (id(this_thermostat).mode == 2) {
            it.image(55, 48, id(snowflake));
            it.printf(0, 49, id(font3), "COOL");
          }
          if (id(this_thermostat).mode == 3) {
            it.image(55, 48, id(fire_icon));
            it.printf(0, 49, id(font3), "HEAT");
          }
          if (id(this_thermostat).mode == 4) {
            it.image(55, 48, id(fan_icon));
            it.printf(0, 49, id(font3), "FAN");
          }
          if (id(this_thermostat).mode == 5) {
            it.image(55, 48, id(water_percent_icon));
            it.printf(0, 49, id(font3), "DRY");
          }
          if (id(this_thermostat).mode == 6) {
            it.image(55, 48, id(refresh_auto));
            it.printf(0, 49, id(font3), "AUTO");
          }
          it.printf(it.get_width(), 0, id(font4), TextAlign::RIGHT, "%.1f°C - %.1f°C", id(this_thermostat).target_temperature_low, id(this_thermostat).target_temperature_high);
      - id: page2
        lambda: |-
          it.filled_circle(50, 50, 10);
      - id: page3
        lambda: |-
          it.filled_rectangle(10, 10, 30, 42);
      - id: page4
        lambda: |-
          it.line(0, 0, 50, 50);
      - id: page5
        lambda: |-
          it.printf(0, 0, id(font1), "Temp: %.1f °C", id(si7021_temperature_sensor).state);
      - id: page6
        lambda: |-
          it.printf(0, 0, id(font1), "Hum: %.1f%%", id(si7021_humidity_sensor).state);
    on_page_change:
      - to: page0
        then:
          - display.page.show: page1
          - component.update: this_display

# Script
script:
  - id: display_on_off
    mode: restart     
    then:
      - lambda: |-
          id(this_display).turn_on();
      - delay: ${display_auto_off_time}
      - lambda: |-
          id(this_display).turn_off();

# Font and images          
font:
  - file: "fonts/thermostat/Montserrat-Regular.ttf"
    id: font1
    size: 18
  - file: "fonts/thermostat/nasalization.ttf"
    id: font2
    size: 32
  - file: "fonts/thermostat/Montserrat-Regular.ttf"
    id: font3
    size: 12
  - file: "fonts/thermostat/Montserrat-Regular.ttf"
    id: font4
    size: 14

image:
  - file: "images/thermostat/wifi-strength-alert-outline.bmp"
    id: wifi_no_signal
    resize: 18x18
  - file: "images/thermostat/wifi-strength-1.bmp"
    id: wifi_1
    resize: 18x18
  - file: "images/thermostat/wifi-strength-2.bmp"
    id: wifi_2
    resize: 18x18
  - file: "images/thermostat/wifi-strength-3.bmp"
    id: wifi_3
    resize: 18x18
  - file: "images/thermostat/wifi-strength-4.bmp"
    id: wifi_4
    resize: 18x18
  - file: "images/thermostat/fire.bmp"
    id: fire_icon
    resize: 18x18
  - file: "images/thermostat/power-standby.bmp"
    id: power_standby_icon
    resize: 18x18
  - file: "images/thermostat/snowflake.bmp"
    id: snowflake
    resize: 18x18
  - file: "images/thermostat/sync.bmp"
    id: sync_icon
    resize: 18x18
  - file: "images/thermostat/water-percent.bmp"
    id: water_percent_icon
    resize: 18x18
  - file: "images/thermostat/fan.bmp"
    id: fan_icon
    resize: 18x18
  - file: "images/thermostat/refresh-auto.bmp"
    id: refresh_auto
    resize: 18x18
   
# Interval
interval:
  - interval: ${wifi_update_interval}
    then:
      if:
        condition:
          wifi.connected:
        then:
          - lambda: |-
              id(my_wifi_status) = true;
        else:
          - lambda: |-
              id(my_wifi_status) = false;